# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '30 * * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
  
    - name: Get current date
      id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d %H:%M')"
      
    - name: Fetch Data and Commit
      run: |
        poetry run python main.py
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GH_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: AutoBuild_${{ steps.date.outputs.today }}
        files: |
          comments.csv